---
title: "Analysis of Shopping Data"
author: "Shilong Dai, Patrick Schmitt, Puyao Ge"
output: html_notebook
---
```{r, echo=T, results="hide"}
#libraries
library(MASS)
library(e1071)
library(caret)
library(rpart)
library(doMC) 
library(popbio)
library(ggplot2)
library(GGally)
library(ggridges)
library(smotefamily)
library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization
library(glmnet)
library(FactoMineR)
registerDoMC(cores = 11) 
```


```{r}
dat <- read.csv("./online_shoppers_intention.csv")
dat$OperatingSystems <- as.factor(dat$OperatingSystems)
dat$Browser <- as.factor(dat$Browser)
dat$Region <- as.factor(dat$Region)
dat$TrafficType <- as.factor(dat$TrafficType)
dat$Weekend <- as.factor(dat$Weekend)
dat$VisitorType <- as.factor(dat$VisitorType)


dat$OperatingSystems <- factor(dat$OperatingSystems, labels = make.names(levels(dat$OperatingSystems)))
dat$Browser <- factor(dat$Browser, labels = make.names(levels(dat$Browser)))
dat$Region <- factor(dat$Region, labels = make.names(levels(dat$Region)))
dat$TrafficType <- factor(dat$TrafficType, labels = make.names(levels(dat$TrafficType)))
dat$Weekend <- factor(dat$Weekend, labels = make.names(levels(dat$Weekend)))
dat$VisitorType <- factor(dat$VisitorType, labels = make.names(levels(dat$VisitorType)))


set.seed(100)
```

```{r}
for (i in c(1:10)) {
  hist(as.vector(dat[,i]), main=colnames(dat)[i])
}
```
```{r}
dat_logged <- as.data.frame(dat)
for (i in c(1:10)) {
  dat_logged[,i] = log(dat[,i]+1)
}
for (i in c(1:10)) {
  hist(dat_logged[,i], main=colnames(dat_logged)[i])
}
```


```{r}
for (i in c(1:10)) {
  dat_logged[,i] = as.vector(scale(dat_logged[, i]))
}
for (i in c(1:10)) {
  hist(dat_logged[,i], main=colnames(dat_logged)[i])
}
```


```{r}
logi.hist.plot(dat_logged$ExitRates,dat_logged$Revenue,boxp=FALSE,type="hist",col="gray")
title("Exitrate vs empirical probability of Revenue")
logi.hist.plot(dat_logged$BounceRates,dat_logged$Revenue,boxp=FALSE,type="hist",col="gray")
title("Bouncerate vs empirical probability of Revenue")
logi.hist.plot(dat_logged$ProductRelated_Duration,dat_logged$Revenue,boxp=FALSE,type="hist",col="gray")
title("ProductRelated_Duration vs empirical probability of Revenue")
logi.hist.plot(dat_logged$ProductRelated,dat_logged$Revenue,boxp=FALSE,type="hist",col="gray")
title("ProductRelated vs empirical probability of Revenue")
logi.hist.plot(dat_logged$SpecialDay, dat_logged$Revenue, boxp = FALSE, type="hist", col="gray")
title("SpecialDay vs empirical probability of Revenue")
logi.hist.plot(dat_logged$PageValues,dat_logged$Revenue,boxp=FALSE,type="hist",col="gray")
title("Page Values vs empirical probability of Revenue")

mosaicplot(Region~Revenue, data=dat_logged)
#region seems to be unimportant on its own
mosaicplot(VisitorType~Revenue, data=dat_logged)
mosaicplot(TrafficType~Revenue, data=dat_logged)
mosaicplot(Month~Revenue, data=dat_logged)
```

#class priors
```{r}
print(paste("Prior probability of Revenue=TRUE: ", sum(dat_logged$Revenue==TRUE)/nrow(dat)))
print(paste("Prior probability of Revenue=FALSE: ", sum(dat_logged$Revenue==FALSE)/nrow(dat)))
```

```{r}
png(filename="bruteforce3.png", width=4096, height=4096)
ggpairs(
  data = dat_logged,
  title = "Pairwise Plot",
  columns = colnames(dat)[1:10],
  upper = list(continuous = "points"),
  mapping = ggplot2::aes(color = Revenue),
  legend = 1
)
dev.off()

```

```{r}
ggplot(dat_logged, aes(x = PageValues, y = TrafficType, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = PageValues, y = Month, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = PageValues, y = VisitorType, fill = Revenue)) +
  geom_density_ridges_gradient()

ggplot(dat_logged, aes(x = BounceRates, y = TrafficType, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = BounceRates, y = Month, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = BounceRates, y = VisitorType, fill = Revenue)) +
  geom_density_ridges_gradient()

ggplot(dat_logged, aes(x = ExitRates, y = TrafficType, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = ExitRates, y = Month, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = ExitRates, y = VisitorType, fill = Revenue)) +
  geom_density_ridges_gradient()

ggplot(dat_logged, aes(x = ProductRelated, y = TrafficType, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = ProductRelated, y = Month, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = ProductRelated, y = VisitorType, fill = Revenue)) +
  geom_density_ridges_gradient()

ggplot(dat_logged, aes(x = ProductRelated_Duration, y = TrafficType, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = ProductRelated_Duration, y = Month, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = ProductRelated_Duration, y = VisitorType, fill = Revenue)) +
  geom_density_ridges_gradient()

ggplot(dat_logged, aes(x = SpecialDay, y = TrafficType, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = SpecialDay, y = Month, fill = Revenue)) +
  geom_density_ridges_gradient()
ggplot(dat_logged, aes(x = SpecialDay, y = VisitorType, fill = Revenue)) +
  geom_density_ridges_gradient()
```

```{r}
dat_numerical <- dat_logged[, -(11:18)]
dat_pcs <- prcomp(dat_numerical, scale = FALSE)
dat_pcs_sum <- summary(dat_pcs)
print(as.data.frame(dat_pcs_sum$importance[, 1:5]))
print(as.data.frame(dat_pcs$rotation))
```

```{r}
dat_pcs_df <- data.frame()
for(i in 1:10) {
  frame <- data.frame(PC = rep(paste0("PC", i), length(dat_pcs$x[, i])),
             Value = dat_pcs$x[, i])
  frame <- cbind(dat_logged["Revenue"], frame)
  dat_pcs_df <- rbind(dat_pcs_df, frame)
}

# How to unfuck this
png(filename="bruteforce2.png", width=4096, height=4096)
ggplot(data = dat_pcs_df, aes(fill = Revenue)) + aes(x = Value) + geom_boxplot() +
  xlab("PC Value") + facet_grid(PC ~ .) + ggtitle("PC Score Distributions")
dev.off()
```

```{r}
pcs <- 10

dat_pcs_pair_df <- data.frame(dat_pcs$x[, 1:10])
dat_pcs_pair_df <- cbind(dat_pcs_pair_df, dat_logged["Revenue"])

head(dat_pcs_pair_df)
png(filename="bruteforce.png", width=4096, height=4096)
ggpairs(
  data = dat_pcs_pair_df,
  title = "Pairwise PC Plot",
  columns = 1:10,
  upper = list(continuous = "points"),
  mapping = ggplot2::aes(color = Revenue),
  legend = 1
)
dev.off()
```

```{r}
k <- 2
k_cluster_2 <-
  kmeans(
    dat_pcs$x,
    centers = k,
    nstart = 25,
    iter.max = 1000
  )
# plots to compare
fviz_2 <-
  fviz_cluster(k_cluster_2, geom = "point", data = dat_pcs$x[, c(1, 5)]) + 
  ggtitle("KMeans Clusters 10 PCs")

print(fviz_2)
```

```{r}
# Summarize results of clustering.
dat_pcs_cluster_df <-
  cbind(dat[, c(18)], k_cluster_2$cluster)
dat_pcs_cluster_df <-as.data.frame(dat_pcs_cluster_df)
colnames(dat_pcs_cluster_df) <- c("Revenue", "Cluster")
dat_pcs_cluster_df[, 1] <- factor(dat_pcs_cluster_df[, 1])
dat_pcs_cluster_df[, 2] <- factor(dat_pcs_cluster_df[, 2])

cluster_bar_2 <-
  ggplot(data = dat_pcs_cluster_df, aes(fill = Revenue)) + aes(x = Cluster) + 
  geom_bar() + xlab("Cluster") + ylab("Count") + ggtitle("Clusters with 10 PCs")
print(cluster_bar_2)
```
```{r}
table(dat_pcs_cluster_df)
```


```{r}
train_size <- floor(0.75 * nrow(dat_logged))
train_ind <- sample(seq_len(nrow(dat_logged)), size = train_size)
train <- dat_logged[train_ind, ]
test <- dat_logged[-train_ind, ]

train$Revenue <- as.factor(train$Revenue)
train$Revenue <- factor(train$Revenue, labels = make.names(levels(train$Revenue)))

test$Revenue <- as.factor(test$Revenue)
test$Revenue <- factor(test$Revenue, labels = make.names(levels(test$Revenue)))

train_numerical <- train[, -(11:18)]
train_pcs <- prcomp(train_numerical, scale = FALSE)

adopted_train <- train[, 1:18]
adopted_train[, 1:10] <- train_pcs$x
colnames(adopted_train)[1:10] <- paste0("PC", 1:10)

head(adopted_train)
head(train)
```


```{r}
test_pcs <- predict(train_pcs, test)

adopted_test <- test[, 1:18]
adopted_test[, 1:10] <- test_pcs
colnames(adopted_test)[1:10] <- paste0("PC", 1:10)
head(adopted_test)
```

```{r}
# Dumy code categorical predictor variables
train_mat <- model.matrix(Revenue~., train)[,-1]
# Convert the outcome (class) to a numerical variable
revenue_vec <- ifelse(train$Revenue == "TRUE.", 1, 0)
```

```{r}
cv.lasso <- cv.glmnet(train_mat, revenue_vec, alpha = 1, family = "binomial")
plot(cv.lasso)
```
```{r}
coef(cv.lasso, cv.lasso$lambda.1se)
```


```{r}
train.control <- trainControl(method = "cv", number = 10)
train_numerical <- train[, c(1:10, 18)]
test_numerical <- test[, c(1:10, 18)]
```

```{r}
train_filtered <- train_numerical[, c(8, 9, 11)]
train_numerical <- as.data.frame(train_filtered)
train_filtered$May <- ifelse(train$Month == "May", 1, 0)
train_filtered$Nov <- ifelse(train$Month == "Nov", 1, 0)
train_filtered$Traffic2 <- ifelse(train$TrafficType == "X2", 1, 0)
train_filtered$Returning <- ifelse(train$VisitorType == "Returning_Visitor", 1, 0)

test_filtered <- test_numerical[, c("ExitRates", "PageValues", "Revenue")]
test_filtered$May <- ifelse(test$Month == "May", 1, 0)
test_filtered$Nov <- ifelse(test$Month == "Nov", 1, 0)
test_filtered$Traffic2 <- ifelse(test$TrafficType == "X2", 1, 0)
test_filtered$Returning <- ifelse(test$VisitorType == "Returning_Visitor", 1, 0)
```


```{r}
tunegrid=data.frame(C=c(seq(0.01, 2, length = 20), 10))
# Train the model
model.cvsvm <- train(Revenue~., data = train_numerical, method = "svmLinear",
               trControl = train.control, tuneGrid = tunegrid, 
               metric = "Kappa")
# Summarize the results
print(model.cvsvm)


predict_svm <- predict(model.cvsvm, test)
cm.svm <-
  confusionMatrix(
    factor(predict_svm),
    factor(test_filtered$Revenue),
    dnn = c("Prediction", "Label"),
    positive="TRUE."
  )
cm.svm
cm.svm$byClass
```


```{r}
model.tree <- train(Revenue~., data = train_filtered, method = "rpart", trControl = train.control, metric = "Kappa")

print(model.tree)

predict_tree <- predict(model.tree, test_filtered)
cm.tree <-
  confusionMatrix(
    factor(predict_tree),
    factor(test_filtered$Revenue),
    dnn = c("Prediction", "Label"),
    positive="TRUE."
  )
cm.tree
cm.tree$byClass
```


```{r}
model.qda <- qda(Revenue~., data = train_numerical)
print(model.qda)

predict_qda <- predict(model.qda, test_filtered)$class
cm.qda <-
  confusionMatrix(
    factor(predict_qda),
    factor(test_filtered$Revenue),
    dnn = c("Prediction", "Label"),
    positive="TRUE."
  )
cm.qda
cm.qda$byClass
```

```{r}
model.glm <- glm(Revenue~., data = train_filtered, family = "binomial")
summary(model.glm)

predict_glm <- predict(model.glm, test_filtered)
predict_glm <- ifelse(predict_glm > 0, "TRUE.", "FALSE.")
predict_glm <- as.factor(predict_glm)

cm.glm <-
  confusionMatrix(
    factor(predict_glm),
    factor(test_filtered$Revenue),
    dnn = c("Prediction", "Label"),
    positive="TRUE."
  )
cm.glm
cm.glm$byClass
```

```{r}
# Dumy code categorical predictor variables
train_mat_pc <- model.matrix(Revenue~., adopted_train)[,-1]
cv.lasso.pc <- cv.glmnet(train_mat_pc, revenue_vec, alpha = 1, family = "binomial")
plot(cv.lasso.pc)
```


```{r}
coef(cv.lasso.pc, cv.lasso.pc$lambda.1se)
```

```{r}
train_numerical_pc <- adopted_train[, c(1:10, 18)]
test_numerical_pc <- adopted_test[, c(1:10, 18)]
train_filtered_pc <- train_numerical_pc[, c(1, 3, 5, 11)]
train_numerical_pc <- as.data.frame(train_filtered_pc)
train_filtered_pc$May <- ifelse(adopted_train$Month == "May", 1, 0)
train_filtered_pc$Nov <- ifelse(adopted_train$Month == "Nov", 1, 0)
train_filtered_pc$Returning <- ifelse(adopted_train$VisitorType == "Returning_Visitor", 1, 0)

test_filtered_pc <- test_numerical_pc[, c(1, 3, 5, 11)]
test_filtered_pc$May <- ifelse(adopted_test$Month == "May", 1, 0)
test_filtered_pc$Nov <- ifelse(adopted_test$Month == "Nov", 1, 0)
test_filtered_pc$Returning <- ifelse(adopted_test$VisitorType == "Returning_Visitor", 1, 0)
```

```{r}
tunegrid=data.frame(C=c(seq(0.01, 2, length = 20), 10))
# Train the model
model.cvsvm <- train(Revenue~., data = train_numerical_pc, method = "svmLinear",
               trControl = train.control, tuneGrid = tunegrid, 
               metric = "Kappa")
# Summarize the results
print(model.cvsvm)


predict_svm <- predict(model.cvsvm, adopted_test)
cm.svm <-
  confusionMatrix(
    factor(predict_svm),
    factor(test_filtered_pc$Revenue),
    dnn = c("Prediction", "Label"),
    positive="TRUE."
  )
cm.svm
cm.svm$byClass
```

```{r}
model.tree <- train(Revenue~., data = train_filtered_pc, method = "rpart", trControl = train.control, metric = "Kappa")

print(model.tree)

predict_tree <- predict(model.tree, test_filtered_pc)
cm.tree <-
  confusionMatrix(
    factor(predict_tree),
    factor(test_filtered_pc$Revenue),
    dnn = c("Prediction", "Label"),
    positive="TRUE."
  )
cm.tree
cm.tree$byClass
```

```{r}
model.qda <- qda(Revenue~., data = train_numerical_pc)
print(model.qda)

predict_qda <- predict(model.qda, test_filtered_pc)$class
cm.qda <-
  confusionMatrix(
    factor(predict_qda),
    factor(test_filtered_pc$Revenue),
    dnn = c("Prediction", "Label"),
    positive="TRUE."
  )
cm.qda
cm.qda$byClass
```

